package cn.gocoxing.ecart.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("ec_cart", "CartID", EcCart.class);
		arp.addMapping("ec_goods", "GoodsID", EcGoods.class);
		arp.addMapping("ec_goods_in_cart", "ID", EcGoodsInCart.class);
		arp.addMapping("ec_market", "MarketID", EcMarket.class);
		arp.addMapping("ec_orders", "OrderID", EcOrders.class);
	}
}

