package cn.gocoxing.ecart.common.model;

import cn.gocoxing.ecart.common.model.base.BaseEcCart;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EcCart extends BaseEcCart<EcCart> {
	
}
