package cn.gocoxing.ecart.common.model;

import cn.gocoxing.ecart.common.model.base.BaseEcGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EcGoods extends BaseEcGoods<EcGoods> {
	public static EcGoods dao = new EcGoods().dao();
}
