package cn.gocoxing.ecart.common.model;

import cn.gocoxing.ecart.common.model.base.BaseEcGoodsInCart;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EcGoodsInCart extends BaseEcGoodsInCart<EcGoodsInCart> {
	public static EcGoodsInCart dao = new EcGoodsInCart().dao();
}
