package cn.gocoxing.ecart.common.model;

import cn.gocoxing.ecart.common.model.base.BaseEcMarket;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EcMarket extends BaseEcMarket<EcMarket> {
	
}
