package cn.gocoxing.ecart.common.model;

import cn.gocoxing.ecart.common.model.base.BaseEcOrders;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EcOrders extends BaseEcOrders<EcOrders> {
	
}
