package cn.gocoxing.ecart.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEcGoodsInCart<M extends BaseEcGoodsInCart<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setCartID(java.lang.String CartID) {
		set("CartID", CartID);
		return (M)this;
	}
	
	public java.lang.String getCartID() {
		return getStr("CartID");
	}

	public M setGoodsID(java.lang.Integer GoodsID) {
		set("GoodsID", GoodsID);
		return (M)this;
	}
	
	public java.lang.Integer getGoodsID() {
		return getInt("GoodsID");
	}

	public M setGoodsPrice(java.lang.Double GoodsPrice) {
		set("GoodsPrice", GoodsPrice);
		return (M)this;
	}
	
	public java.lang.Double getGoodsPrice() {
		return getDouble("GoodsPrice");
	}

	public M setQuantity(java.lang.Double Quantity) {
		set("Quantity", Quantity);
		return (M)this;
	}
	
	public java.lang.Double getQuantity() {
		return getDouble("Quantity");
	}

	public M setGoodsStatus(java.lang.Integer GoodsStatus) {
		set("GoodsStatus", GoodsStatus);
		return (M)this;
	}
	
	public java.lang.Integer getGoodsStatus() {
		return getInt("GoodsStatus");
	}

	public M setPutInTime(java.util.Date PutInTime) {
		set("PutInTime", PutInTime);
		return (M)this;
	}
	
	public java.util.Date getPutInTime() {
		return get("PutInTime");
	}

	public M setTakeOutTime(java.util.Date TakeOutTime) {
		set("TakeOutTime", TakeOutTime);
		return (M)this;
	}
	
	public java.util.Date getTakeOutTime() {
		return get("TakeOutTime");
	}

}
