package cn.gocoxing.ecart.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEcOrders<M extends BaseEcOrders<M>> extends Model<M> implements IBean {

	public M setOrderID(java.lang.Integer OrderID) {
		set("OrderID", OrderID);
		return (M)this;
	}
	
	public java.lang.Integer getOrderID() {
		return getInt("OrderID");
	}

	public M setOrderNo(java.lang.String OrderNo) {
		set("OrderNo", OrderNo);
		return (M)this;
	}
	
	public java.lang.String getOrderNo() {
		return getStr("OrderNo");
	}

	public M setPayProvider(java.lang.Integer PayProvider) {
		set("PayProvider", PayProvider);
		return (M)this;
	}
	
	public java.lang.Integer getPayProvider() {
		return getInt("PayProvider");
	}

	public M setBuyerLogonId(java.lang.String buyerLogonId) {
		set("buyer_logon_id", buyerLogonId);
		return (M)this;
	}
	
	public java.lang.String getBuyerLogonId() {
		return getStr("buyer_logon_id");
	}

	public M setTotalAmount(java.lang.Double totalAmount) {
		set("total_amount", totalAmount);
		return (M)this;
	}
	
	public java.lang.Double getTotalAmount() {
		return getDouble("total_amount");
	}

	public M setReceiptAmount(java.lang.Double receiptAmount) {
		set("receipt_amount", receiptAmount);
		return (M)this;
	}
	
	public java.lang.Double getReceiptAmount() {
		return getDouble("receipt_amount");
	}

	public M setInvoiceAmount(java.lang.Double invoiceAmount) {
		set("invoice_amount", invoiceAmount);
		return (M)this;
	}
	
	public java.lang.Double getInvoiceAmount() {
		return getDouble("invoice_amount");
	}

	public M setBuyerPayAmount(java.lang.Double buyerPayAmount) {
		set("buyer_pay_amount", buyerPayAmount);
		return (M)this;
	}
	
	public java.lang.Double getBuyerPayAmount() {
		return getDouble("buyer_pay_amount");
	}

	public M setCreateDate(java.util.Date CreateDate) {
		set("CreateDate", CreateDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("CreateDate");
	}

}
