package cn.gocoxing.ecart.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEcPayRecord<M extends BaseEcPayRecord<M>> extends Model<M> implements IBean {

	public M setPayID(java.lang.Integer PayID) {
		set("PayID", PayID);
		return (M)this;
	}
	
	public java.lang.Integer getPayID() {
		return getInt("PayID");
	}

}
