package cn.gocoxing.ecart.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEcCart<M extends BaseEcCart<M>> extends Model<M> implements IBean {

	public M setCartID(java.lang.String CartID) {
		set("CartID", CartID);
		return (M)this;
	}
	
	public java.lang.String getCartID() {
		return getStr("CartID");
	}

	public M setMarketID(java.lang.Integer MarketID) {
		set("MarketID", MarketID);
		return (M)this;
	}
	
	public java.lang.Integer getMarketID() {
		return getInt("MarketID");
	}

}
