package cn.gocoxing.ecart.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEcGoods<M extends BaseEcGoods<M>> extends Model<M> implements IBean {

	public M setGoodsID(java.lang.Integer GoodsID) {
		set("GoodsID", GoodsID);
		return (M)this;
	}
	
	public java.lang.Integer getGoodsID() {
		return getInt("GoodsID");
	}

	public M setBarcode(java.lang.Long Barcode) {
		set("Barcode", Barcode);
		return (M)this;
	}
	
	public java.lang.Long getBarcode() {
		return getLong("Barcode");
	}

	public M setGoodsName(java.lang.String GoodsName) {
		set("GoodsName", GoodsName);
		return (M)this;
	}
	
	public java.lang.String getGoodsName() {
		return getStr("GoodsName");
	}

	public M setGoodsUnit(java.lang.String GoodsUnit) {
		set("GoodsUnit", GoodsUnit);
		return (M)this;
	}
	
	public java.lang.String getGoodsUnit() {
		return getStr("GoodsUnit");
	}

	public M setGoodsPrice(java.lang.Double GoodsPrice) {
		set("GoodsPrice", GoodsPrice);
		return (M)this;
	}
	
	public java.lang.Double getGoodsPrice() {
		return getDouble("GoodsPrice");
	}

	public M setGoodsPic(java.lang.String GoodsPic) {
		set("GoodsPic", GoodsPic);
		return (M)this;
	}
	
	public java.lang.String getGoodsPic() {
		return getStr("GoodsPic");
	}

}
